// =============================================================
// BASE DE DONNÉES DES 100 ALLIÉS À COLLECTIONNER (alliesData.js)
// 4 Paliers de rareté x 25 Alliés = 100 Figures de Lutte
// =============================================================

const ALLIES_DATABASE = [

    // =============================================================
    // PALIER 1 : MILITANT DE TERRAIN (Indices 1 à 25)
    // Couleur : Vert (#16a34a)
    // Bonus : Apport fixe (+5 000 à +15 000 manifestants)
    // =============================================================
    {
        id: "momo_benali",
        name: "Momo Benali",
        role: "Patron de Zinc Popu",
        tier: 1,
        rarityName: "Militant de Terrain",
        rarityColor: "#16a34a",
        scoreIndex: 10,
        archetype: "Syndicaliste / Populaire",
        bonusType: "flat",
        bonusValue: 5000,
        bio: "Patron de café de quartier populaire, hébergeur des réunions syndicales et des caisses de grève solidaires."
    },
    {
        id: "claire_vigneron",
        name: "Claire Vigneron",
        role: "Paysanne Bio",
        tier: 1,
        rarityName: "Militant de Terrain",
        rarityColor: "#16a34a",
        scoreIndex: 11,
        archetype: "Paysanne Bio",
        bonusType: "flat",
        bonusValue: 5500,
        bio: "Maraîchère de la Confédération Paysanne, créatrice de marchés solidaires et d'invendus à prix libre."
    },
    {
        id: "sebastien_maillet",
        name: "Sébastien Maillet",
        role: "Ouvrier d'Usine",
        tier: 1,
        rarityName: "Militant de Terrain",
        rarityColor: "#16a34a",
        scoreIndex: 12,
        archetype: "Ouvrier d'Usine",
        bonusType: "flat",
        bonusValue: 6000,
        bio: "Ouvrier verrier syndiqué, mobilisé sans relâche contre les délocalisations industrielles."
    },
    {
        id: "maxence_leroux",
        name: "Maxence Leroux",
        role: "Étudiant Bloqueur",
        tier: 1,
        rarityName: "Militant de Terrain",
        rarityColor: "#16a34a",
        scoreIndex: 12,
        archetype: "Étudiant Bloqueur",
        bonusType: "flat",
        bonusValue: 6000,
        bio: "Étudiant en AG, organisateur des cordons d'autodéfense et des caisses de solidarité étudiante."
    },
    {
        id: "christian_sunt",
        name: "Christian Sunt",
        role: "Bâtisseur d'AMAP",
        tier: 1,
        rarityName: "Militant de Terrain",
        rarityColor: "#16a34a",
        scoreIndex: 13,
        archetype: "Écologie Populaire",
        bonusType: "flat",
        bonusValue: 6500,
        bio: "Pionnier des AMAP en France, artisan de l'alliance directe entre citadins et petits producteurs paysans."
    },
    {
        id: "gaetan_morel",
        name: "Gaëtan Morel",
        role: "Écureuil des Cimes",
        tier: 1,
        rarityName: "Militant de Terrain",
        rarityColor: "#16a34a",
        scoreIndex: 14,
        archetype: "ZADiste / Climat",
        bonusType: "flat",
        bonusValue: 7000,
        bio: "Militant perché des semaines dans les arbres centenaires pour bloquer les pelleteuses d'autoroute."
    },
    {
        id: "ines_belkacem",
        name: "Inès Belkacem",
        role: "Féministe Nocturne",
        tier: 1,
        rarityName: "Militant de Terrain",
        rarityColor: "#16a34a",
        scoreIndex: 14,
        archetype: "Féministe de Nuit",
        bonusType: "flat",
        bonusValue: 7000,
        bio: "Militante de nuit, colleuse de lettres noires sur fond blanc pour visibiliser les violences patriarcales."
    },
    {
        id: "genevieve_legay",
        name: "Geneviève Legay",
        role: "Aînée Indignée",
        tier: 1,
        rarityName: "Militant de Terrain",
        rarityColor: "#16a34a",
        scoreIndex: 15,
        archetype: "Libertés Publiques",
        bonusType: "flat",
        bonusValue: 7500,
        bio: "Militante Attac de 73 ans blessée à Nice en 2019, devenue le symbole de la défense du droit constitutionnel de manifester."
    },
    {
        id: "fatou_dieng",
        name: "Fatou Dieng",
        role: "Sentinelle Justice",
        tier: 1,
        rarityName: "Militant de Terrain",
        rarityColor: "#16a34a",
        scoreIndex: 15,
        archetype: "Vérité & Justice",
        bonusType: "flat",
        bonusValue: 7500,
        bio: "Co-fondatrice du collectif Vies Volées, engagée aux côtés des familles de victimes de violences policières."
    },
    {
        id: "youssef_rahmani",
        name: "Youssef Rahmani",
        role: "Livreur à Vélo",
        tier: 1,
        rarityName: "Militant de Terrain",
        rarityColor: "#16a34a",
        scoreIndex: 15,
        archetype: "Travailleur Ubérisé",
        bonusType: "flat",
        bonusValue: 8000,
        bio: "Coursier à vélo, organisateur des débrayages sauvages contre les algorithmes prédateurs des plateformes."
    },
    {
        id: "stephane_ravacley",
        name: "Stéphane Ravacley",
        role: "Artisan Solidaire",
        tier: 1,
        rarityName: "Militant de Terrain",
        rarityColor: "#16a34a",
        scoreIndex: 16,
        archetype: "Artisan Solidaire",
        bonusType: "flat",
        bonusValue: 8500,
        bio: "Boulanger de Besançon, gréviste de la faim héroïque pour empêcher l'expulsion injuste de son jeune apprenti guinéen."
    },
    {
        id: "youcef_brakni",
        name: "Youcef Brakni",
        role: "Voix des Quartiers",
        tier: 1,
        rarityName: "Militant de Terrain",
        rarityColor: "#16a34a",
        scoreIndex: 16,
        archetype: "Quartiers Populaires",
        bonusType: "flat",
        bonusValue: 8500,
        bio: "Militant antiraciste des banlieues populaires et animateur des comités de vérité et de justice citoyenne."
    },
    {
        id: "jean_baptiste_eyraud",
        name: "Jean-Baptiste Eyraud",
        role: "Réquisitionneur Urbain",
        tier: 1,
        rarityName: "Militant de Terrain",
        rarityColor: "#16a34a",
        scoreIndex: 17,
        archetype: "Droit au Logement",
        bonusType: "flat",
        bonusValue: 9000,
        bio: "Co-fondateur historique du DAL, pionnier des ouvertures d'immeubles vides pour abriter les familles mal-logées."
    },
    {
        id: "cedric_herrou",
        name: "Cédric Herrou",
        role: "Paysan Solidaire",
        tier: 1,
        rarityName: "Militant de Terrain",
        rarityColor: "#16a34a",
        scoreIndex: 18,
        archetype: "Paysan Solidaire",
        bonusType: "flat",
        bonusValue: 10000,
        bio: "Agriculteur de la vallée de la Roya, artisan de la fin du délit de solidarité et de l'accueil digne des personnes exilées."
    },
    {
        id: "mickael_wamen",
        name: "Mickaël Wamen",
        role: "Métallo en Colère",
        tier: 1,
        rarityName: "Militant de Terrain",
        rarityColor: "#16a34a",
        scoreIndex: 18,
        archetype: "Métallo en Colère",
        bonusType: "flat",
        bonusValue: 10000,
        bio: "Leader syndical CGT de l'usine Goodyear Amiens, symbole du combat ouvrier contre les fermetures boursières de sites."
    },
    {
        id: "priscillia_ludosky",
        name: "Priscillia Ludosky",
        role: "Citoyenne des Ronds-Points",
        tier: 1,
        rarityName: "Militant de Terrain",
        rarityColor: "#16a34a",
        scoreIndex: 19,
        archetype: "Pouvoir d'Achat",
        bonusType: "flat",
        bonusValue: 11000,
        bio: "Initiatrice de la pétition originelle contre les taxes carburant inégales, figure de la justice fiscale populaire."
    },
    {
        id: "gabriel_amard",
        name: "Gabriel Amard",
        role: "Défenseur de l'Eau Publique",
        tier: 1,
        rarityName: "Militant de Terrain",
        rarityColor: "#16a34a",
        scoreIndex: 19,
        archetype: "Biens Communs",
        bonusType: "flat",
        bonusValue: 11000,
        bio: "Élu de terrain et spécialiste de la régie publique de l'eau face aux appétits des multinationales privées."
    },
    {
        id: "rachel_keke",
        name: "Rachel Keke",
        role: "Ouvrière Combattive",
        tier: 1,
        rarityName: "Militant de Terrain",
        rarityColor: "#16a34a",
        scoreIndex: 20,
        archetype: "Femmes de Chambre en Lutte",
        bonusType: "flat",
        bonusValue: 12500,
        bio: "Gouvernante de l'hôtel Ibis Batignolles, meneuse de la plus longue grève victorieuse de l'histoire hôtelière."
    },
    {
        id: "gerard_filoche",
        name: "Gérard Filoche",
        role: "Sentinelle du Travail",
        tier: 1,
        rarityName: "Militant de Terrain",
        rarityColor: "#16a34a",
        scoreIndex: 20,
        archetype: "Code du Travail",
        bonusType: "flat",
        bonusValue: 12500,
        bio: "Ancien inspecteur du travail, vulgarisateur passionné des droits ouvriers face aux abus patronaux."
    },
    {
        id: "danielle_simonnet",
        name: "Danielle Simonnet",
        role: "Élue de Proximité",
        tier: 1,
        rarityName: "Militant de Terrain",
        rarityColor: "#16a34a",
        scoreIndex: 20,
        archetype: "Élue de Terrain",
        bonusType: "flat",
        bonusValue: 12500,
        bio: "Élue de quartier, engagée sur le terrain auprès des sans-papiers, des squats et des travailleuses du nettoyage."
    },
    {
        id: "melanie_luce",
        name: "Mélanie Luce",
        role: "Cadre Syndicale Jeunesse",
        tier: 1,
        rarityName: "Militant de Terrain",
        rarityColor: "#16a34a",
        scoreIndex: 21,
        archetype: "Syndicalisme Étudiant",
        bonusType: "flat",
        bonusValue: 13000,
        bio: "Ancienne présidente syndicale étudiante, artisane des victoires sur le gel des frais d'inscription et le repas Crous."
    },
    {
        id: "dominique_bourg",
        name: "Dominique Bourg",
        role: "Penseur de la Terre",
        tier: 1,
        rarityName: "Militant de Terrain",
        rarityColor: "#16a34a",
        scoreIndex: 22,
        archetype: "Écologie Politique",
        bonusType: "flat",
        bonusValue: 13500,
        bio: "Philosophe de l'environnement, théoricien de la démocratie écologique et du respect absolu des limites planétaires."
    },
    {
        id: "alma_dufour",
        name: "Alma Dufour",
        role: "Tacticienne Anti-Multinationales",
        tier: 1,
        rarityName: "Militant de Terrain",
        rarityColor: "#16a34a",
        scoreIndex: 23,
        archetype: "Action Directe Écolo",
        bonusType: "flat",
        bonusValue: 14000,
        bio: "Ancienne porte-parole des Amis de la Terre, stratège des blocages d'entrepôts Amazon devenue députée de rupture."
    },
    {
        id: "benoit_biteau",
        name: "Benoît Biteau",
        role: "Agronome Paysan",
        tier: 1,
        rarityName: "Militant de Terrain",
        rarityColor: "#16a34a",
        scoreIndex: 24,
        archetype: "Défenseur de l'Eau",
        bonusType: "flat",
        bonusValue: 14500,
        bio: "Paysan agronome et député, figure nationale de l'opposition paysanne aux méga-bassines industrielles."
    },
    {
        id: "arie_alimi",
        name: "Arié Alimi",
        role: "Avocat de Rupture",
        tier: 1,
        rarityName: "Militant de Terrain",
        rarityColor: "#16a34a",
        scoreIndex: 25,
        archetype: "Défense des Libertés",
        bonusType: "flat",
        bonusValue: 15000,
        bio: "Avocat au barreau de Paris, défenseur infatigable des manifestants nassés et des familles de victimes."
    },

    // =============================================================
    // PALIER 2 : CADRE DE LUTTE (Théoriciens & Réseau - 25 Alliés)
    // Couleur : Bleu (#2563eb)
    // Bonus : Multiplicateur modéré (+15% à +25% de manifestants)
    // =============================================================
    {
        id: "bernard_friot",
        name: "Bernard Friot",
        role: "Théoricien du Salaire à Vie",
        tier: 2,
        rarityName: "Cadre de Lutte",
        rarityColor: "#2563eb",
        scoreIndex: 26,
        archetype: "Économiste Social",
        bonusType: "multiplier",
        bonusValue: 0.15,
        bio: "Sociologue et économiste, créateur du modèle du « Salaire à vie » et de la Sécurité Sociale de l'Alimentation."
    },
    {
        id: "wassim_dz",
        name: "Wassim (Wassim_DZ)",
        role: "Enquêteur Numérique",
        tier: 2,
        rarityName: "Cadre de Lutte",
        rarityColor: "#2563eb",
        scoreIndex: 27,
        archetype: "Enquête OSINT",
        bonusType: "multiplier",
        bonusValue: 0.15,
        bio: "Enquêteur citoyen OSINT sur les réseaux, traqueur des violences policières et de la propagande d'extrême droite."
    },
    {
        id: "clementine_autain",
        name: "Clémentine Autain",
        role: "Féministe de Lutte",
        tier: 2,
        rarityName: "Cadre de Lutte",
        rarityColor: "#2563eb",
        scoreIndex: 28,
        archetype: "Émancipation Féministe",
        bonusType: "multiplier",
        bonusValue: 0.15,
        bio: "Militante féministe historique, cofondatrice de Mix-Cité et porte-voix des luttes d'émancipation populaire."
    },
    {
        id: "pincon_charlot",
        name: "Monique & Michel Pinçon-Charlot",
        role: "Sociologues de Classe",
        tier: 2,
        rarityName: "Cadre de Lutte",
        rarityColor: "#2563eb",
        scoreIndex: 29,
        archetype: "Sociologie Critique",
        bonusType: "multiplier",
        bonusValue: 0.15,
        bio: "Sociologues spécialistes de la grande bourgeoisie et des mécanismes de reproduction et de domination de classe."
    },
    {
        id: "andreas_malm",
        name: "Andreas Malm",
        role: "Stratège de Rupture Climat",
        tier: 2,
        rarityName: "Cadre de Lutte",
        rarityColor: "#2563eb",
        scoreIndex: 30,
        archetype: "Autodéfense Écologique",
        bonusType: "multiplier",
        bonusValue: 0.15,
        bio: "Chercheur suédois en écologie humaine, théoricien de l'autodéfense écologique et du désarmement des infrastructures fossiles."
    },
    {
        id: "andre_gorz",
        name: "André Gorz",
        role: "Pionnier Écologie Politique",
        tier: 2,
        rarityName: "Cadre de Lutte",
        rarityColor: "#2563eb",
        scoreIndex: 31,
        archetype: "Écologie Radicale",
        bonusType: "multiplier",
        bonusValue: 0.15,
        bio: "Penseur majeur de l'écologie de rupture et pionnier de la réduction drastique du temps de travail aliénant."
    },
    {
        id: "francoise_deaubonne",
        name: "Françoise d'Eaubonne",
        role: "Mère de l'Écoféminisme",
        tier: 2,
        rarityName: "Cadre de Lutte",
        rarityColor: "#2563eb",
        scoreIndex: 32,
        archetype: "Écoféminisme Historique",
        bonusType: "multiplier",
        bonusValue: 0.15,
        bio: "Pionnière écologiste française ayant inventé et conceptualisé le terme « Écoféminisme » dès 1974."
    },
    {
        id: "david_graeber",
        name: "David Graeber",
        role: "Anthropologue Anarchiste",
        tier: 2,
        rarityName: "Cadre de Lutte",
        rarityColor: "#2563eb",
        scoreIndex: 33,
        archetype: "Démocratie Directe",
        bonusType: "multiplier",
        bonusValue: 0.15,
        bio: "Anthropologue américain, figure d'Occupy Wall Street et théoricien brillant des « Bullshit Jobs » et de la dette."
    },
    {
        id: "frederic_lordon",
        name: "Frédéric Lordon",
        role: "Philosophe Anticapitaliste",
        tier: 2,
        rarityName: "Cadre de Lutte",
        rarityColor: "#2563eb",
        scoreIndex: 34,
        archetype: "Sortie du Capitalisme",
        bonusType: "multiplier",
        bonusValue: 0.18,
        bio: "Économiste et philosophe spinoziste, analyste tranchant de la tyrannie financière et de la nécessité de la rupture."
    },
    {
        id: "elinor_ostrom",
        name: "Elinor Ostrom",
        role: "Économiste des Communs",
        tier: 2,
        rarityName: "Cadre de Lutte",
        rarityColor: "#2563eb",
        scoreIndex: 35,
        archetype: "Biens Communs",
        bonusType: "multiplier",
        bonusValue: 0.18,
        bio: "Première femme Prix Nobel d'économie, théoricienne de la gestion citoyenne et collective des biens communs."
    },
    {
        id: "vandana_shiva",
        name: "Vandana Shiva",
        role: "Gardienne des Semences",
        tier: 2,
        rarityName: "Cadre de Lutte",
        rarityColor: "#2563eb",
        scoreIndex: 36,
        archetype: "Écologie Paysanne",
        bonusType: "multiplier",
        bonusValue: 0.18,
        bio: "Physicienne et écologiste indienne, figure mondiale de la sauvegarde des semences paysannes libres face aux brevets industriels."
    },
    {
        id: "murray_bookchin",
        name: "Murray Bookchin",
        role: "Penseur de l'Écologie Sociale",
        tier: 2,
        rarityName: "Cadre de Lutte",
        rarityColor: "#2563eb",
        scoreIndex: 37,
        archetype: "Municipalisme Libertaire",
        bonusType: "multiplier",
        bonusValue: 0.18,
        bio: "Philosophe libertaire américain, père de l'« Écologie sociale » et du municipalisme d'assemblée directe."
    },
    {
        id: "thomas_sankara",
        name: "Thomas Sankara",
        role: "Révolutionnaire Panafricain",
        tier: 2,
        rarityName: "Cadre de Lutte",
        rarityColor: "#2563eb",
        scoreIndex: 38,
        archetype: "Anti-Impérialisme",
        bonusType: "multiplier",
        bonusValue: 0.20,
        bio: "Président du Burkina Faso, champion de l'annulation de la dette coloniale, de l'autosuffisance et de la reforestation."
    },
    {
        id: "frantz_fanon",
        name: "Frantz Fanon",
        role: "Penseur Décolonial",
        tier: 2,
        rarityName: "Cadre de Lutte",
        rarityColor: "#2563eb",
        scoreIndex: 39,
        archetype: "Anticolonialisme",
        bonusType: "multiplier",
        bonusValue: 0.20,
        bio: "Psychiatre martiniquais, auteur des « Damnés de la Terre », phare universel de la libération des peuples colonisés."
    },
    {
        id: "silvia_federici",
        name: "Silvia Federici",
        role: "Théoricienne Autonome",
        tier: 2,
        rarityName: "Cadre de Lutte",
        rarityColor: "#2563eb",
        scoreIndex: 40,
        archetype: "Féminisme Révolutionnaire",
        bonusType: "multiplier",
        bonusValue: 0.20,
        bio: "Universitaire féministe, autrice de « Caliban et la Sorcière », théoricienne du travail reproductif et domestique invisible."
    },
    {
        id: "sarah_durieux",
        name: "Sarah Durieux",
        role: "Stratège des Pétitions",
        tier: 2,
        rarityName: "Cadre de Lutte",
        rarityColor: "#2563eb",
        scoreIndex: 41,
        archetype: "Mobilisation Web",
        bonusType: "multiplier",
        bonusValue: 0.20,
        bio: "Experte des mobilisations numériques, coordinatrice de campagnes citoyennes majeures sur le web."
    },
    {
        id: "paul_guillibert",
        name: "Paul Guillibert",
        role: "Théoricien Écosocialiste",
        tier: 2,
        rarityName: "Cadre de Lutte",
        rarityColor: "#2563eb",
        scoreIndex: 42,
        archetype: "Écosocialisme",
        bonusType: "multiplier",
        bonusValue: 0.20,
        bio: "Philosophe universitaire, auteur de référence sur l'écosocialisme et le communisme de préservation du vivant."
    },
    {
        id: "regelegorila",
        name: "Regelegorila",
        role: "Streamer Populaire",
        tier: 2,
        rarityName: "Cadre de Lutte",
        rarityColor: "#2563eb",
        scoreIndex: 43,
        archetype: "Culture Twitch",
        bonusType: "multiplier",
        bonusValue: 0.22,
        bio: "Streamer et créateur web, célèbre pour ses tier-lists politiques tranchées et ses réactions sans langue de bois."
    },
    {
        id: "glupatate",
        name: "Glupatate",
        role: "Monteur Satirique",
        tier: 2,
        rarityName: "Cadre de Lutte",
        rarityColor: "#2563eb",
        scoreIndex: 44,
        archetype: "Zapping Satirique",
        bonusType: "multiplier",
        bonusValue: 0.22,
        bio: "Monteur satirique indépendant, créateur des zappings mèmes les plus viraux contre les éditorialistes réactionnaires."
    },
    {
        id: "gilles_perret",
        name: "Gilles Perret",
        role: "Cinéaste du Peuple",
        tier: 2,
        rarityName: "Cadre de Lutte",
        rarityColor: "#2563eb",
        scoreIndex: 45,
        archetype: "Cinéma Documentaire",
        bonusType: "multiplier",
        bonusValue: 0.22,
        bio: "Cinéaste ouvrier, réalisateur de « La Sociale » et documentariste des grandes conquêtes syndicales françaises."
    },
    {
        id: "merwane_benlazar",
        name: "Merwane Benlazar",
        role: "Humoriste Engagé",
        tier: 2,
        rarityName: "Cadre de Lutte",
        rarityColor: "#2563eb",
        scoreIndex: 46,
        archetype: "Stand-Up Populaire",
        bonusType: "multiplier",
        bonusValue: 0.25,
        bio: "Humoriste de stand-up et chroniqueur, maître de l'autodérision sociale et de la riposte antiraciste."
    },
    {
        id: "akim_omiri",
        name: "Akim Omiri",
        role: "Humoriste Solidaire",
        tier: 2,
        rarityName: "Cadre de Lutte",
        rarityColor: "#2563eb",
        scoreIndex: 47,
        archetype: "Stand-Up Solidaire",
        bonusType: "multiplier",
        bonusValue: 0.25,
        bio: "Comédien engagé, organisateur de grands galas d'humour au profit direct des caisses de grève ouvrières."
    },
    {
        id: "kimberle_crenshaw",
        name: "Kimberlé Crenshaw",
        role: "Théoricienne de l'Intersectionnalité",
        tier: 2,
        rarityName: "Cadre de Lutte",
        rarityColor: "#2563eb",
        scoreIndex: 48,
        archetype: "Juriste de l'Intersectionnalité",
        bonusType: "multiplier",
        bonusValue: 0.25,
        bio: "Juriste et universitaire américaine ayant théorisé le concept fondamental d'« Intersectionnalité » en 1989."
    },
    {
        id: "usul",
        name: "Usul",
        role: "Chroniqueur Critique",
        tier: 2,
        rarityName: "Cadre de Lutte",
        rarityColor: "#2563eb",
        scoreIndex: 49,
        archetype: "Analyse Politique Web",
        bonusType: "multiplier",
        bonusValue: 0.25,
        bio: "Chroniqueur vidéo et essayiste marxiste, pionnier de l'analyse politique indépendante et populaire sur le web."
    },
    {
        id: "vikash_dhorasoo",
        name: "Vikash Dhorasoo",
        role: "Athlète Populaire",
        tier: 2,
        rarityName: "Cadre de Lutte",
        rarityColor: "#2563eb",
        scoreIndex: 50,
        archetype: "Sport Populaire",
        bonusType: "multiplier",
        bonusValue: 0.25,
        bio: "Ancien footballeur international, cofondateur du mouvement Tatane pour un football populaire et citoyen."
    },

    // =============================================================
    // PALIER 3 : POIDS LOURD (Figures Reconnues & Médias - 25 Alliés)
    // Couleur : Violet (#9333ea)
    // Bonus : Multiplicateur solide (+35% à +50% de manifestants)
    // =============================================================
    {
        id: "salome_saque",
        name: "Salomé Saqué",
        role: "Journaliste de Rupture",
        tier: 3,
        rarityName: "Poids Lourd",
        rarityColor: "#9333ea",
        scoreIndex: 51,
        archetype: "Journalisme Climat",
        bonusType: "multiplier",
        bonusValue: 0.35,
        bio: "Journaliste d'investigation économique et climatique à Blast, autrice engagée sur la défense de la jeunesse."
    },
    {
        id: "clement_viktorovitch",
        name: "Clément Viktorovitch",
        role: "Analyste Rhétorique",
        tier: 3,
        rarityName: "Poids Lourd",
        rarityColor: "#9333ea",
        scoreIndex: 52,
        archetype: "Décryptage du Discours",
        bonusType: "multiplier",
        bonusValue: 0.35,
        bio: "Docteur en sciences politiques, spécialiste du décryptage rhétorique et de la déconstruction de la novlangue."
    },
    {
        id: "jean_massiet",
        name: "Jean Massiet",
        role: "Vulgarisateur Twitch",
        tier: 3,
        rarityName: "Poids Lourd",
        rarityColor: "#9333ea",
        scoreIndex: 53,
        archetype: "Twitch Politique",
        bonusType: "multiplier",
        bonusValue: 0.35,
        bio: "Créateur de l'émission Backseat sur Twitch, vulgarisateur du fonctionnement parlementaire et citoyen."
    },
    {
        id: "aymeric_caron",
        name: "Aymeric Caron",
        role: "Défenseur du Vivant",
        tier: 3,
        rarityName: "Poids Lourd",
        rarityColor: "#9333ea",
        scoreIndex: 54,
        archetype: "Antispécisme Politique",
        bonusType: "multiplier",
        bonusValue: 0.35,
        bio: "Journaliste et député, fondateur de la REV, pionnier de l'antispécisme et de la protection du vivant au parlement."
    },
    {
        id: "ludivine_bantigny",
        name: "Ludivine Bantigny",
        role: "Historienne des Révoltes",
        tier: 3,
        rarityName: "Poids Lourd",
        rarityColor: "#9333ea",
        scoreIndex: 55,
        archetype: "Histoire Populaire",
        bonusType: "multiplier",
        bonusValue: 0.35,
        bio: "Historienne des mouvements sociaux, autrice majeure sur les dynamiques de désobéissance et de grève générale."
    },
    {
        id: "meurice_dia",
        name: "Guillaume Meurice & Waly Dia",
        role: "Satiristes Clandestins",
        tier: 3,
        rarityName: "Poids Lourd",
        rarityColor: "#9333ea",
        scoreIndex: 56,
        archetype: "Satire Politique",
        bonusType: "multiplier",
        bonusValue: 0.38,
        bio: "Duo d'humoristes politiques exilés de la radio publique, maîtres de l'insolence face aux puissants."
    },
    {
        id: "sebastien_delogu",
        name: "Sébastien Delogu",
        role: "Tribune des Quartiers",
        tier: 3,
        rarityName: "Poids Lourd",
        rarityColor: "#9333ea",
        scoreIndex: 57,
        archetype: "Quartiers & Palestine",
        bonusType: "multiplier",
        bonusValue: 0.38,
        bio: "Député marseillais, ancien chauffeur de taxi, défenseur intransigeant des quartiers populaires et de la Palestine."
    },
    {
        id: "cecile_duflot",
        name: "Cécile Duflot",
        role: "Dirigeante Anti-Pauvreté",
        tier: 3,
        rarityName: "Poids Lourd",
        rarityColor: "#9333ea",
        scoreIndex: 58,
        archetype: "Justice Fiscale Oxfam",
        bonusType: "multiplier",
        bonusValue: 0.38,
        bio: "Directrice générale d'Oxfam France, fer de lance de la dénonciation de l'enrichissement indécent des ultra-milliardaires."
    },
    {
        id: "david_dufresne",
        name: "David Dufresne",
        role: "Documentariste d'État",
        tier: 3,
        rarityName: "Poids Lourd",
        rarityColor: "#9333ea",
        scoreIndex: 59,
        archetype: "Maintien de l'Ordre",
        bonusType: "multiplier",
        bonusValue: 0.40,
        bio: "Écrivain et réalisateur d'« Un pays qui se tient sage », documentariste de référence des violences d'État."
    },
    {
        id: "philippe_poutou",
        name: "Philippe Poutou",
        role: "Tribune Ouvrière",
        tier: 3,
        rarityName: "Poids Lourd",
        rarityColor: "#9333ea",
        scoreIndex: 60,
        archetype: "Ouvrier Combattif",
        bonusType: "multiplier",
        bonusValue: 0.40,
        bio: "Ouvrier de l'automobile, porte-parole anticapitaliste au franc-parler légendaire face aux politiciens de carrière."
    },
    {
        id: "eric_fassin",
        name: "Éric Fassin",
        role: "Sociologue Émancipateur",
        tier: 3,
        rarityName: "Poids Lourd",
        rarityColor: "#9333ea",
        scoreIndex: 61,
        archetype: "Sociologie Critique",
        bonusType: "multiplier",
        bonusValue: 0.40,
        bio: "Sociologue engagé, chercheur sur les politiques sexuelles, les minorités et la sociologie de la désobéissance."
    },
    {
        id: "medine",
        name: "Médine",
        role: "Poète du Pavé",
        tier: 3,
        rarityName: "Poids Lourd",
        rarityColor: "#9333ea",
        scoreIndex: 62,
        archetype: "Rap Engagé",
        bonusType: "multiplier",
        bonusValue: 0.42,
        bio: "Rappeur indépendant et auteur, figure de l'expression populaire et des concerts de soutien aux quartiers."
    },
    {
        id: "rima_hassan",
        name: "Rima Hassan",
        role: "Juriste Internationale",
        tier: 3,
        rarityName: "Poids Lourd",
        rarityColor: "#9333ea",
        scoreIndex: 63,
        archetype: "Droit International",
        bonusType: "multiplier",
        bonusValue: 0.42,
        bio: "Juriste en droit international, réfugiée palestinienne, eurodéputée portant la voix inconditionnelle des peuples opprimés."
    },
    {
        id: "sandrine_rousseau",
        name: "Sandrine Rousseau",
        role: "Écoféministe Radicale",
        tier: 3,
        rarityName: "Poids Lourd",
        rarityColor: "#9333ea",
        scoreIndex: 64,
        archetype: "Écoféminisme de Rupture",
        bonusType: "multiplier",
        bonusValue: 0.45,
        bio: "Économiste universitaire et députée, théoricienne du ralentissement écologique et de la rupture patriarcale."
    },
    {
        id: "shada_nasser",
        name: "Shada Nasser",
        role: "Avocate de la Liberté",
        tier: 3,
        rarityName: "Poids Lourd",
        rarityColor: "#9333ea",
        scoreIndex: 65,
        archetype: "Droits des Femmes",
        bonusType: "multiplier",
        bonusValue: 0.45,
        bio: "Avocate yéménite pionnière, héroïne de l'abolition du mariage forcé des fillettes et de l'émancipation légale."
    },
    {
        id: "mona_chollet",
        name: "Mona Chollet",
        role: "Autrice Féministe Majeure",
        tier: 3,
        rarityName: "Poids Lourd",
        rarityColor: "#9333ea",
        scoreIndex: 66,
        archetype: "Littérature Émancipatrice",
        bonusType: "multiplier",
        bonusValue: 0.45,
        bio: "Autrice culte de « Sorcières » et « Chez soi », figure majeure de la pensée féministe et de la critique du capitalisme intime."
    },
    {
        id: "sophie_binet",
        name: "Sophie Binet",
        role: "Secrétaire Générale CGT",
        tier: 3,
        rarityName: "Poids Lourd",
        rarityColor: "#9333ea",
        scoreIndex: 67,
        archetype: "Grève Générale",
        bonusType: "multiplier",
        bonusValue: 0.45,
        bio: "Secrétaire générale de la CGT, cadre issue du monde éducatif, visage de l'intersyndicale et de la combativité sociale."
    },
    {
        id: "louis_boyard",
        name: "Louis Boyard",
        role: "Agitateur Étudiant",
        tier: 3,
        rarityName: "Poids Lourd",
        rarityColor: "#9333ea",
        scoreIndex: 68,
        archetype: "Tribune Jeunesse",
        bonusType: "multiplier",
        bonusValue: 0.48,
        bio: "Député de la jeunesse, organisateur des blocages étudiants et du combat pour le repas Crous universel à 1€."
    },
    {
        id: "ken_loach",
        name: "Ken Loach",
        role: "Cinéaste Prolétarien",
        tier: 3,
        rarityName: "Poids Lourd",
        rarityColor: "#9333ea",
        scoreIndex: 69,
        archetype: "Cinéma Social International",
        bonusType: "multiplier",
        bonusValue: 0.48,
        bio: "Deux fois Palme d'Or à Cannes, cinéaste légendaire de la classe ouvrière britannique et des luttes contre l'austérité."
    },
    {
        id: "arundhati_roy",
        name: "Arundhati Roy",
        role: "Romancière Combattante",
        tier: 3,
        rarityName: "Poids Lourd",
        rarityColor: "#9333ea",
        scoreIndex: 70,
        archetype: "Résistance Populaire Indienne",
        bonusType: "multiplier",
        bonusValue: 0.48,
        bio: "Écrivaine indienne majeure, figure de la résistance aux barrages géants, au nationalisme religieux et à l'impérialisme armé."
    },
    {
        id: "manuel_bompard",
        name: "Manuel Bompard",
        role: "Cerveau Électoral",
        tier: 3,
        rarityName: "Poids Lourd",
        rarityColor: "#9333ea",
        scoreIndex: 71,
        archetype: "Stratégie Politique",
        bonusType: "multiplier",
        bonusValue: 0.50,
        bio: "Mathématicien et député, organisateur clé des campagnes populaires et de l'union des forces de rupture."
    },
    {
        id: "chantal_mouffe",
        name: "Chantal Mouffe",
        role: "Penseuse de la Démocratie Radicale",
        tier: 3,
        rarityName: "Poids Lourd",
        rarityColor: "#9333ea",
        scoreIndex: 72,
        archetype: "Populisme de Gauche",
        bonusType: "multiplier",
        bonusValue: 0.50,
        bio: "Philosophe politique belge, théoricienne du populisme de gauche, de l'hégémonie et de la démocratie conflictuelle."
    },
    {
        id: "mathilde_panot",
        name: "Mathilde Panot",
        role: "Stratège Parlementaire",
        tier: 3,
        rarityName: "Poids Lourd",
        rarityColor: "#9333ea",
        scoreIndex: 73,
        archetype: "Riposte Parlementaire",
        bonusType: "multiplier",
        bonusValue: 0.50,
        bio: "Présidente de groupe parlementaire, cheffe d'orchestre des motions de censure contre les décrets d'austérité du pouvoir."
    },
    {
        id: "judith_butler",
        name: "Judith Butler",
        role: "Théoricienne Queer",
        tier: 3,
        rarityName: "Poids Lourd",
        rarityColor: "#9333ea",
        scoreIndex: 74,
        archetype: "Théorie Queer & Genre",
        bonusType: "multiplier",
        bonusValue: 0.50,
        bio: "Philosophe américaine, fondatrice des études de genre et du concept de performativité des identités sexuées."
    },
    {
        id: "thomas_piketty",
        name: "Thomas Piketty",
        role: "Économiste Mondial",
        tier: 3,
        rarityName: "Poids Lourd",
        rarityColor: "#9333ea",
        scoreIndex: 75,
        archetype: "Redistribution Radicale",
        bonusType: "multiplier",
        bonusValue: 0.50,
        bio: "Auteur du best-seller « Le Capital au XXIe siècle », théoricien mondial de la fiscalité progressive des patrimoines."
    },

    // =============================================================
    // PALIER 4 : LÉGENDE HISTORIQUE (Figures Mondiales & Rupture - 25 Alliés)
    // Couleur : Doré (#d97706)
    // Bonus : Multiplicateur historique (+55% à +100% de cortège)
    // =============================================================
    {
        id: "achille_mbembe",
        name: "Achille Mbembe",
        role: "Théoricien Postcolonial",
        tier: 4,
        rarityName: "Légende Historique",
        rarityColor: "#d97706",
        scoreIndex: 76,
        archetype: "Nécropolitique",
        bonusType: "multiplier",
        bonusValue: 0.55,
        bio: "Historien et politologue camerounais, inventeur du concept fondamental de « Nécropolitique » sur le contrôle des corps."
    },
    {
        id: "angela_davis",
        name: "Angela Davis",
        role: "Icône Révolutionnaire",
        tier: 4,
        rarityName: "Légende Historique",
        rarityColor: "#d97706",
        scoreIndex: 77,
        archetype: "Abolitionnisme Carcéral",
        bonusType: "multiplier",
        bonusValue: 0.60,
        bio: "Philosophe marxiste américaine, légende vivante des luttes antiracistes, féministes et de l'abolitionnisme carcéral."
    },
    {
        id: "naomi_klein",
        name: "Naomi Klein",
        role: "Analyste du Choc",
        tier: 4,
        rarityName: "Légende Historique",
        rarityColor: "#d97706",
        scoreIndex: 78,
        archetype: "Capitalisme de Désastre",
        bonusType: "multiplier",
        bonusValue: 0.60,
        bio: "Essayiste canadienne, autrice de « La Stratégie du choc », analyste majeure de l'exploitation capitaliste des crises."
    },
    {
        id: "esther_duflo",
        name: "Esther Duflo",
        role: "Nobel d'Économie Solidaire",
        tier: 4,
        rarityName: "Légende Historique",
        rarityColor: "#d97706",
        scoreIndex: 79,
        archetype: "Économie Expérimentale",
        bonusType: "multiplier",
        bonusValue: 0.65,
        bio: "Prix Nobel d'économie, pionnière des programmes expérimentaux mondiaux d'éradication de l'extrême pauvreté."
    },
    {
        id: "greta_thunberg",
        name: "Greta Thunberg",
        role: "Voix du Climat",
        tier: 4,
        rarityName: "Légende Historique",
        rarityColor: "#d97706",
        scoreIndex: 80,
        archetype: "Grève Mondiale Climat",
        bonusType: "multiplier",
        bonusValue: 0.70,
        bio: "Initiatrice de la grève mondiale scolaire pour le climat, visage de la désobéissance de masse face aux lobbys fossiles."
    },
    {
        id: "berta_caceres",
        name: "Berta Cáceres",
        role: "Martyre des Fleuves",
        tier: 4,
        rarityName: "Légende Historique",
        rarityColor: "#d97706",
        scoreIndex: 81,
        archetype: "Écologie Autochtone",
        bonusType: "multiplier",
        bonusValue: 0.75,
        bio: "Militante écologiste lenca hondurienne assassinée pour avoir défendu les cours d'eau sacrés face aux mégabarrages."
    },
    {
        id: "frida_kahlo",
        name: "Frida Kahlo",
        role: "Icône de l'Art Engagé",
        tier: 4,
        rarityName: "Légende Historique",
        rarityColor: "#d97706",
        scoreIndex: 82,
        archetype: "Art Révolutionnaire",
        bonusType: "multiplier",
        bonusValue: 0.75,
        bio: "Artiste peintre révolutionnaire et militante communiste mexicaine, symbole mondial de résilience corporelle et de liberté."
    },
    {
        id: "chico_mendes",
        name: "Chico Mendes",
        role: "Gardien de l'Amazonie",
        tier: 4,
        rarityName: "Légende Historique",
        rarityColor: "#d97706",
        scoreIndex: 83,
        archetype: "Défense de la Forêt",
        bonusType: "multiplier",
        bonusValue: 0.75,
        bio: "Syndicaliste paysan brésilien, bâtisseur de l'alliance des peuples de la forêt assassiné pour la protection de l'Amazonie."
    },
    {
        id: "alexandria_ocasio_cortez",
        name: "Alexandria Ocasio-Cortez (AOC)",
        role: "Porte-Voix du Bronx",
        tier: 4,
        rarityName: "Légende Historique",
        rarityColor: "#d97706",
        scoreIndex: 84,
        archetype: "Green New Deal US",
        bonusType: "multiplier",
        bonusValue: 0.80,
        bio: "Élue du Congrès américain, cheffe de file du Green New Deal et de l'essor du syndicalisme chez les jeunes travailleurs."
    },
    {
        id: "zohran_mamdani",
        name: "Zohran Mamdani",
        role: "Maire Populaire de New York",
        tier: 4,
        rarityName: "Légende Historique",
        rarityColor: "#d97706",
        scoreIndex: 85,
        archetype: "Socialisme Municipal NYC",
        bonusType: "multiplier",
        bonusValue: 0.80,
        bio: "Maire socialiste démocrate de New York, pionnier du gel des loyers, de la gratuité totale des bus et des épiceries publiques."
    },
    {
        id: "emiliano_zapata",
        name: "Emiliano Zapata",
        role: "Cavalier de la Terre et Liberté",
        tier: 4,
        rarityName: "Légende Historique",
        rarityColor: "#d97706",
        scoreIndex: 86,
        archetype: "Terre & Liberté",
        bonusType: "multiplier",
        bonusValue: 0.80,
        bio: "Général de la révolution mexicaine de 1910, auteur du Plan d'Ayala pour la restitution intégrale des terres aux indigènes."
    },
    {
        id: "che_guevara",
        name: "Ernesto Che Guevara",
        role: "Guérillero Internationaliste",
        tier: 4,
        rarityName: "Légende Historique",
        rarityColor: "#d97706",
        scoreIndex: 87,
        archetype: "Révolution Mondiale",
        bonusType: "multiplier",
        bonusValue: 0.85,
        bio: "Médecin et commandant révolutionnaire internationaliste, symbole mondial de la lutte armée contre l'impérialisme."
    },
    {
        id: "salvador_allende",
        name: "Salvador Allende",
        role: "Président Martyr de la Démocratie",
        tier: 4,
        rarityName: "Légende Historique",
        rarityColor: "#d97706",
        scoreIndex: 88,
        archetype: "Voie Démocratique au Socialisme",
        bonusType: "multiplier",
        bonusValue: 0.85,
        bio: "Président socialiste chilien démocratiquement élu, mort l'arme à la main lors du coup d'État militaire de Pinochet en 1973."
    },
    {
        id: "simone_de_beauvoir",
        name: "Simone de Beauvoir",
        role: "Phare Existentialiste",
        tier: 4,
        rarityName: "Légende Historique",
        rarityColor: "#d97706",
        scoreIndex: 89,
        archetype: "Émancipation Existentialiste",
        bonusType: "multiplier",
        bonusValue: 0.85,
        bio: "Philosophe existentialiste, autrice du « Deuxième Sexe », théoricienne de la liberté radicale et de l'émancipation féminine."
    },
    {
        id: "bernie_sanders",
        name: "Bernie Sanders",
        role: "Socialiste Démocrate US",
        tier: 4,
        rarityName: "Légende Historique",
        rarityColor: "#d97706",
        scoreIndex: 90,
        archetype: "Révolution Politique US",
        bonusType: "multiplier",
        bonusValue: 0.85,
        bio: "Sénateur indépendant américain, figure de proue de la lutte pour la santé publique gratuite et contre l'oligarchie financière."
    },
    {
        id: "rosa_luxemburg",
        name: "Rosa Luxemburg",
        role: "Étoile Révolutionnaire",
        tier: 4,
        rarityName: "Légende Historique",
        rarityColor: "#d97706",
        scoreIndex: 91,
        archetype: "Grève de Masse",
        bonusType: "multiplier",
        bonusValue: 0.90,
        bio: "Économiste et révolutionnaire marxiste, figure intransigeante du pacifisme international et de la démocratie socialiste."
    },
    {
        id: "ambroise_croizat",
        name: "Ambroise Croizat",
        role: "Bâtisseur de la Sécu",
        tier: 4,
        rarityName: "Légende Historique",
        rarityColor: "#d97706",
        scoreIndex: 92,
        archetype: "Sécurité Sociale",
        bonusType: "multiplier",
        bonusValue: 0.90,
        bio: "Ouvrier métallurgiste et ministre communiste du Travail, architecte et fondateur de la Sécurité Sociale en 1945."
    },
    {
        id: "gisele_halimi",
        name: "Gisèle Halimi",
        role: "Avocate Insoumise",
        tier: 4,
        rarityName: "Légende Historique",
        rarityColor: "#d97706",
        scoreIndex: 93,
        archetype: "Procès Historiques Féministes",
        bonusType: "multiplier",
        bonusValue: 0.95,
        bio: "Avocate historique du procès de Bobigny, signataire du Manifeste des 343, artisane de la dépénalisation de l'avortement."
    },
    {
        id: "rosa_parks",
        name: "Rosa Parks",
        role: "Étincelle des Droits Civiques",
        tier: 4,
        rarityName: "Légende Historique",
        rarityColor: "#d97706",
        scoreIndex: 94,
        archetype: "Droits Civiques US",
        bonusType: "multiplier",
        bonusValue: 0.95,
        bio: "Militante des droits civiques dont le refus historique de céder sa place dans un bus a allumé le grand boycott de Montgomery."
    },
    {
        id: "harriet_tubman",
        name: "Harriet Tubman",
        role: "Guide de la Liberté",
        tier: 4,
        rarityName: "Légende Historique",
        rarityColor: "#d97706",
        scoreIndex: 95,
        archetype: "Chemin de la Liberté",
        bonusType: "multiplier",
        bonusValue: 0.95,
        bio: "Esclave évadée devenue conductrice héroïque du réseau clandestin Underground Railroad pour libérer des centaines d'esclaves."
    },
    {
        id: "louise_michel",
        name: "Louise Michel",
        role: "Vierge Rouge de la Commune",
        tier: 4,
        rarityName: "Légende Historique",
        rarityColor: "#d97706",
        scoreIndex: 96,
        archetype: "Commune de Paris 1871",
        bonusType: "multiplier",
        bonusValue: 1.00,
        bio: "Institutrice anarchiste, héroïne de la Commune de Paris de 1871, combattante des barricades et de l'éducation populaire."
    },
    {
        id: "nelson_mandela",
        name: "Nelson Mandela",
        role: "Libérateur des Peuples",
        tier: 4,
        rarityName: "Légende Historique",
        rarityColor: "#d97706",
        scoreIndex: 97,
        archetype: "Fin de l'Apartheid",
        bonusType: "multiplier",
        bonusValue: 1.00,
        bio: "Leader de l'ANC, prisonnier politique pendant 27 ans à Robben Island, artisan victorieux de l'abolition de l'Apartheid."
    },
    {
        id: "martin_luther_king",
        name: "Martin Luther King Jr.",
        role: "Apôtre de la Justice Civique",
        tier: 4,
        rarityName: "Légende Historique",
        rarityColor: "#d97706",
        scoreIndex: 98,
        archetype: "Droits Civiques & Paix",
        bonusType: "multiplier",
        bonusValue: 1.00,
        bio: "Pasteur et figure monumentale de la lutte pour les droits civiques, auteur du discours « I Have a Dream » et de la marche contre la pauvreté."
    },
    {
        id: "jean_jaures",
        name: "Jean Jaurès",
        role: "Phare Républicain",
        tier: 4,
        rarityName: "Légende Historique",
        rarityColor: "#d97706",
        scoreIndex: 99,
        archetype: "Socialisme Républicain",
        bonusType: "multiplier",
        bonusValue: 1.00,
        bio: "Fondateur du journal L'Humanité, orateur pacifiste martyr de 1914 et bâtisseur du socialisme républicain démocratique."
    },
    {
        id: "karl_marx",
        name: "Karl Marx",
        role: "Père du Socialisme Scientifique",
        tier: 4,
        rarityName: "Légende Historique",
        rarityColor: "#d97706",
        scoreIndex: 100,
        archetype: "Matérialisme Historique",
        bonusType: "multiplier",
        bonusValue: 1.00,
        bio: "Philosophe, économiste et journaliste, auteur du « Capital », théoricien fondamental de la lutte des classes et de l'émancipation prolétarienne."
    }
];